import 'package:flutter/foundation.dart';
import 'package:shared_preferences/shared_preferences.dart';

class LanguageService {
  static const String _prefKey = 'selected_language_code';

  /// ValueNotifier holding current language code ('en', 'mr', 'hi')
  static final ValueNotifier<String> currentLanguage = ValueNotifier<String>('en');

  /// Initialize language setting from SharedPreferences
  static Future<void> initLanguage() async {
    final prefs = await SharedPreferences.getInstance();
    final savedCode = prefs.getString(_prefKey) ?? 'en';
    currentLanguage.value = savedCode;
  }

  /// Change language and persist preference
  static Future<void> setLanguage(String code) async {
    if (code != 'en' && code != 'mr' && code != 'hi') return;
    currentLanguage.value = code;
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString(_prefKey, code);
  }

  /// Translate a string key into selected language
  static String tr(String key) {
    final lang = currentLanguage.value;
    final normalizedKey = key.toLowerCase().trim().replaceAll(' ', '_');
    return _translations[lang]?[normalizedKey] ??
        _translations[lang]?[key] ??
        _translations['en']?[normalizedKey] ??
        _translations['en']?[key] ??
        key;
  }

  static final Map<String, Map<String, String>> _translations = {
    'en': {
      'app_title': 'Maharashtra Tyres',
      'tagline': 'Tyre Shop Billing & Inventory System',
      'dashboard': 'Dashboard',
      'customers': 'Customers',
      'inventory': 'Inventory',
      'sales': 'Sales',
      'invoices': 'Invoices',
      'reminders': 'Reminders',
      'reports': 'Reports',
      'revenue': 'Revenue',
      'suppliers': 'Suppliers',
      'notifications': 'Notifications',
      'settings': 'Settings',
      'language': 'Language',
      'select_language': 'Select Language',
      'english': 'English',
      'marathi': 'Marathi (मराठी)',
      'hindi': 'Hindi (हिंदी)',
      'good_morning': 'Good Morning',
      'todays_sales': "Today's Sales",
      'todays_orders': "Today's Orders",
      'products': 'Products',
      'recent_sales': 'Recent Sales',
      'low_stock_alert': 'Low Stock Alert',
      'quick_actions': 'Quick Actions',
      'add_customer': 'Add Customer',
      'edit_customer': 'Edit Customer',
      'update_customer': 'Update Customer',
      'new_sale': 'New Sale',
      'generate_invoice': 'Generate Invoice',
      'edit_invoice': 'Edit Invoice',
      'update_invoice': 'Update Invoice',
      'view_all_sales': 'View All Sales',
      'view_inventory': 'View Inventory',
      'left_in_stock': 'Left in stock',
      'logout': 'Logout',
      'profile': 'Profile',
      'dark_mode': 'Dark Mode',
      'light_mode': 'Light Mode',
      'theme_settings': 'Theme & Appearance',
      'app_version': 'App Version',
      'privacy_policy': 'Privacy Policy',
      'help_support': 'Help & Support',

      // Sign Up & Auth
      'login': 'Login',
      'sign_up': 'Sign Up',
      'create_account': 'Create Business Account',
      'welcome_back': 'Welcome Back!',
      'email_or_phone': 'Email or Mobile Number',
      'password': 'Password',
      'confirm_password': 'Confirm Password',
      'shop_name': 'Shop Name / Firm Name',
      'full_name': 'Full Name',
      'remember_me': 'Remember Me',
      'forgot_password': 'Forgot Password?',
      'login_with_otp': 'Login with OTP',
      'send_otp': 'Send OTP',
      'verify_otp': 'Verify OTP',
      'enter_otp': 'Enter 6-digit OTP',
      'dont_have_account': "Don't have an account?",
      'already_have_account': 'Already have an account?',
      'register_now': 'Register Now',
      'passwords_dont_match': 'Passwords do not match',

      // Customers
      'customer_list': 'Customer Directory',
      'search_customers': 'Search by name, phone, or city...',
      'phone': 'Phone Number',
      'email': 'Email Address',
      'address': 'Address',
      'city': 'City',
      'vehicle_no': 'Vehicle Number',
      'edit': 'Edit',
      'delete': 'Delete',
      'total_customers': 'Total Customers',
      'no_customers_found': 'No customers found',
      'add_new_customer': 'Add New Customer',
      'edit_customer_details': 'Edit Customer Details',

      // Inventory
      'inventory_stock': 'Inventory Stock',
      'add_product': 'Add New Product',
      'edit_product': 'Edit Product',
      'update_product': 'Update Product',
      'search_products': 'Search product or brand...',
      'product_name': 'Product Name',
      'brand': 'Brand / Company',
      'quantity': 'Quantity',
      'price': 'Price (₹)',
      'stock_status': 'Stock Status',
      'in_stock': 'In Stock',
      'out_of_stock': 'Out of Stock',
      'low_stock': 'Low Stock',
      'active_stock': 'Active Stock',
      'inactive_stock': 'Inactive Stock',

      // Invoices
      'all_invoices': 'All Invoices',
      'create_invoice': 'Create Invoice',
      'search_invoices': 'Search by invoice no or customer...',
      'invoice_number': 'Invoice No.',
      'customer_name': 'Customer Name',
      'amount': 'Amount',
      'date': 'Date',
      'due_date': 'Due Date',
      'status': 'Status',
      'paid': 'Paid',
      'pending': 'Pending',
      'cancelled': 'Cancelled',
      'download_pdf': 'Download PDF',
      'share': 'Share',
      'customer_details': 'Customer Details',
      'invoice_details': 'Invoice Details',
      'invoice_items': 'Invoice Items',
      'item_description': 'Item Description',
      'subtotal': 'Subtotal',
      'tax': 'Tax / GST',
      'discount': 'Discount',
      'total': 'Total Amount',
      'notes': 'Notes',
      'save': 'Save',
      'cancel': 'Cancel',
      'select_product': 'Select Product',

      // Sales
      'sales_dashboard': 'Sales Dashboard',
      'total_revenue': 'Total Revenue',
      'completed_sales': 'Completed Sales',
      'monthly_overview': 'Monthly Sales Overview',

      // Reminders
      'overdue_reminders': 'Overdue Payment Reminders',
      'send_whatsapp_reminder': 'Send WhatsApp Reminder',
      'mark_as_settled': 'Mark as Settled',
    },
    'mr': {
      'app_title': 'महाराष्ट्र टायर्स',
      'tagline': 'टायर शॉप बिलिंग आणि इन्व्हेंटरी सिस्टीम',
      'dashboard': 'डॅशबोर्ड',
      'customers': 'ग्राहक',
      'inventory': 'इन्व्हेंटरी',
      'sales': 'विक्री',
      'invoices': 'पावत्या',
      'reminders': 'स्मरणपत्रे',
      'reports': 'अहवाल',
      'revenue': 'महसूल',
      'suppliers': 'पुरवठादार',
      'notifications': 'सूचना',
      'settings': 'सेटिंग्ज',
      'language': 'भाषा',
      'select_language': 'भाषा निवडा',
      'english': 'English (इंग्रजी)',
      'marathi': 'मराठी (Marathi)',
      'hindi': 'हिंदी (Hindi)',
      'good_morning': 'शुभ सकाळ',
      'todays_sales': 'आजची विक्री',
      'todays_orders': 'आजच्या ऑर्डर्स',
      'products': 'उत्पादने',
      'recent_sales': 'अलीकडील विक्री',
      'low_stock_alert': 'कमी स्टॉक इशारे',
      'quick_actions': 'जलद कृती',
      'add_customer': 'ग्राहक जोडा',
      'edit_customer': 'ग्राहक संपादित करा',
      'update_customer': 'ग्राहक अपडेट करा',
      'new_sale': 'नवीन विक्री',
      'generate_invoice': 'पावती तयार करा',
      'edit_invoice': 'पावती संपादित करा',
      'update_invoice': 'पावती अपडेट करा',
      'view_all_sales': 'सर्व विक्री पहा',
      'view_inventory': 'इन्व्हेंटरी पहा',
      'left_in_stock': 'शिल्लक',
      'logout': 'लॉग आउट',
      'profile': 'प्रोफाइल',
      'dark_mode': 'डार्क मोड',
      'light_mode': 'लाइट मोड',
      'theme_settings': 'थीम आणि देखावा',
      'app_version': 'ॲप आवृत्ती',
      'privacy_policy': 'गोपनीयता धोरण',
      'help_support': 'मदत केंद्र',

      // Sign Up & Auth
      'login': 'लॉगिन करा',
      'sign_up': 'साइन अप करा',
      'create_account': 'नवीन खाते तयार करा',
      'welcome_back': 'सुस्वागतम!',
      'email_or_phone': 'ईमेल किंवा मोबाईल नंबर',
      'password': 'पासवर्ड',
      'confirm_password': 'पासवर्डची पुष्टी करा',
      'shop_name': 'दुकानाचे नाव / फर्मचे नाव',
      'full_name': 'संपूर्ण नाव',
      'remember_me': 'माझी माहिती आठवणीत ठेवा',
      'forgot_password': 'पासवर्ड विसरलात?',
      'login_with_otp': 'OTP द्वारे लॉगिन करा',
      'send_otp': 'OTP पाठवा',
      'verify_otp': 'OTP सत्यापित करा',
      'enter_otp': '६-अंकी OTP प्रविष्ट करा',
      'dont_have_account': 'खाते नाही का?',
      'already_have_account': 'आधीच खाते आहे का?',
      'register_now': 'आत्ता नोंदणी करा',
      'passwords_dont_match': 'पासवर्ड जुळत नाहीत',

      // Customers
      'customer_list': 'ग्राहक यादी',
      'search_customers': 'नाव, फोन किंवा शहरानुसार शोधा...',
      'phone': 'मोबाईल नंबर',
      'email': 'ईमेल पत्ता',
      'address': 'पत्ता',
      'city': 'शहर',
      'vehicle_no': 'गाडी क्रमांक',
      'edit': 'संपादन करा',
      'delete': 'हटवा',
      'total_customers': 'एकूण ग्राहक',
      'no_customers_found': 'कोणतेही ग्राहक सापडले नाहीत',
      'add_new_customer': 'नवीन ग्राहक जोडा',
      'edit_customer_details': 'ग्राहक माहिती संपादित करा',

      // Inventory
      'inventory_stock': 'इन्व्हेंटरी स्टॉक',
      'add_product': 'नवीन उत्पादन जोडा',
      'edit_product': 'उत्पादन संपादित करा',
      'update_product': 'उत्पादन अपडेट करा',
      'search_products': 'उत्पादन किंवा ब्रँडनुसार शोधा...',
      'product_name': 'उत्पादनाचे नाव',
      'brand': 'ब्रँड / कंपनी',
      'quantity': 'प्रमाण (नग)',
      'price': 'किंमत (₹)',
      'stock_status': 'स्टॉक स्थिती',
      'in_stock': 'उपलब्ध स्टॉक',
      'out_of_stock': 'स्टॉक संपला',
      'low_stock': 'कमी स्टॉक',
      'active_stock': 'सक्रिय स्टॉक',
      'inactive_stock': 'निष्क्रिय स्टॉक',

      // Invoices
      'all_invoices': 'सर्व पावत्या',
      'create_invoice': 'नवीन पावती तयार करा',
      'search_invoices': 'पावती क्रमांक किंवा ग्राहकाद्वारे शोधा...',
      'invoice_number': 'पावती क्रमांक',
      'customer_name': 'ग्राहकाचे नाव',
      'amount': 'रक्कम',
      'date': 'दिनांक',
      'due_date': 'देय दिनांक',
      'status': 'स्थिती',
      'paid': 'भरले',
      'pending': 'बाकी',
      'cancelled': 'रद्द',
      'download_pdf': 'PDF डाउनलोड',
      'share': 'शेअर करा',
      'customer_details': 'ग्राहकाची माहिती',
      'invoice_details': 'पावतीची माहिती',
      'invoice_items': 'पावती वस्तू',
      'item_description': 'वस्तूचे वर्णन',
      'subtotal': 'उप-एकूण रक्कम',
      'tax': 'कर (Tax)',
      'discount': 'सवलत (Discount)',
      'total': 'एकूण रक्कम',
      'notes': 'टीप',
      'save': 'जतन करा',
      'cancel': 'रद्द करा',
      'select_product': 'उत्पादन निवडा',

      // Sales
      'sales_dashboard': 'विक्री डॅशबोर्ड',
      'total_revenue': 'एकूण महसूल',
      'completed_sales': 'पूर्ण झालेली विक्री',
      'monthly_overview': 'मासिक विक्री आढावा',

      // Reminders
      'overdue_reminders': 'थकित पेमेंट स्मरणपत्रे',
      'send_whatsapp_reminder': 'WhatsApp स्मरणपत्र पाठवा',
      'mark_as_settled': 'जमा म्हणून चिन्हांकित करा',
    },
    'hi': {
      'app_title': 'महाराष्ट्र टायर्स',
      'tagline': 'टायर शॉप बिलिंग और इन्वेंटरी सिस्टम',
      'dashboard': 'डैशबोर्ड',
      'customers': 'ग्राहक',
      'inventory': 'इन्वेंटरी',
      'sales': 'बिक्री',
      'invoices': 'बिल / रसीद',
      'reminders': 'रिमाइंडर्स',
      'reports': 'रिपोर्ट्स',
      'revenue': 'राजस्व',
      'suppliers': 'सप्लायर्स',
      'notifications': 'सूचनाएं',
      'settings': 'सेटिंग्स',
      'language': 'भाषा',
      'select_language': 'भाषा चुनें',
      'english': 'English (अंग्रेजी)',
      'marathi': 'मराठी (Marathi)',
      'hindi': 'हिंदी (Hindi)',
      'good_morning': 'शुभ प्रभात',
      'todays_sales': 'आज की बिक्री',
      'todays_orders': 'आज के ऑर्डर्स',
      'products': 'उत्पाद',
      'recent_sales': 'हाल की बिक्री',
      'low_stock_alert': 'कम स्टॉक अलर्ट',
      'quick_actions': 'त्वरित कार्रवाई',
      'add_customer': 'ग्राहक जोड़ें',
      'edit_customer': 'ग्राहक संपादित करें',
      'update_customer': 'ग्राहक अपडेट करें',
      'new_sale': 'नई बिक्री',
      'generate_invoice': 'बिल बनाएं',
      'edit_invoice': 'बिल संपादित करें',
      'update_invoice': 'बिल अपडेट करें',
      'view_all_sales': 'सभी बिक्री देखें',
      'view_inventory': 'इन्वेंटरी देखें',
      'left_in_stock': 'स्टॉक में शेष',
      'logout': 'लॉग आउट',
      'profile': 'प्रोफाइल',
      'dark_mode': 'डार्क मोड',
      'light_mode': 'लाइट मोड',
      'theme_settings': 'थीम और स्वरूप',
      'app_version': 'ऐप संस्करण',
      'privacy_policy': 'गोपनीयता नीति',
      'help_support': 'सहायता केंद्र',

      // Sign Up & Auth
      'login': 'लॉगिन',
      'sign_up': 'साइन अप',
      'create_account': 'व्यापार खाता बनाएं',
      'welcome_back': 'स्वागत है!',
      'email_or_phone': 'ईमेल या मोबाइल नंबर',
      'password': 'पासवर्ड',
      'confirm_password': 'पासवर्ड की पुष्टि करें',
      'shop_name': 'दुकान / फर्म का नाम',
      'full_name': 'पूरा नाम',
      'remember_me': 'मुझे याद रखें',
      'forgot_password': 'पासवर्ड भूल गए?',
      'login_with_otp': 'OTP से लॉगिन करें',
      'send_otp': 'OTP भेजें',
      'verify_otp': 'OTP सत्यापित करें',
      'enter_otp': '६-अंकों का OTP दर्ज करें',
      'dont_have_account': 'खाता नहीं है?',
      'already_have_account': 'पहले से खाता है?',
      'register_now': 'अभी रजिस्टर करें',
      'passwords_dont_match': 'पासवर्ड मेल नहीं खाते',

      // Customers
      'customer_list': 'ग्राहक सूची',
      'search_customers': 'नाम, फोन या शहर से खोजें...',
      'phone': 'मोबाइल नंबर',
      'email': 'ईमेल पता',
      'address': 'पता',
      'city': 'शहर',
      'vehicle_no': 'वाहन नंबर',
      'edit': 'संपादित करें',
      'delete': 'हटाएं',
      'total_customers': 'कुल ग्राहक',
      'no_customers_found': 'कोई ग्राहक नहीं मिला',
      'add_new_customer': 'नया ग्राहक जोड़ें',
      'edit_customer_details': 'ग्राहक विवरण संपादित करें',

      // Inventory
      'inventory_stock': 'इन्वेंटरी स्टॉक',
      'add_product': 'नया उत्पाद जोड़ें',
      'edit_product': 'उत्पाद संपादित करें',
      'update_product': 'उत्पाद अपडेट करें',
      'search_products': 'उत्पाद या ब्रांड से खोजें...',
      'product_name': 'उत्पाद का नाम',
      'brand': 'ब्रांड / कंपनी',
      'quantity': 'मात्रा',
      'price': 'मूल्य (₹)',
      'stock_status': 'स्टॉक स्थिति',
      'in_stock': 'स्टॉक में उपलब्ध',
      'out_of_stock': 'स्टॉक समाप्त',
      'low_stock': 'कम स्टॉक',
      'active_stock': 'सक्रिय स्टॉक',
      'inactive_stock': 'निष्क्रिय स्टॉक',

      // Invoices
      'all_invoices': 'सभी बिल',
      'create_invoice': 'नया बिल बनाएं',
      'search_invoices': 'बिल नंबर या ग्राहक से खोजें...',
      'invoice_number': 'बिल नंबर',
      'customer_name': 'ग्राहक का नाम',
      'amount': 'राशि',
      'date': 'दिनांक',
      'due_date': 'देय तिथि',
      'status': 'स्थिति',
      'paid': 'भुगतान किया',
      'pending': 'बकाया',
      'cancelled': 'रद्द',
      'download_pdf': 'PDF डाउनलोड करें',
      'share': 'शेयर करें',
      'customer_details': 'ग्राहक विवरण',
      'invoice_details': 'बिल विवरण',
      'invoice_items': 'बिल की वस्तुएं',
      'item_description': 'विवरण',
      'subtotal': 'उप-कुल',
      'tax': 'कर (GST)',
      'discount': 'छूट (Discount)',
      'total': 'कुल राशि',
      'notes': 'टिप्पणी',
      'save': 'सहेजें',
      'cancel': 'रद्द करें',
      'select_product': 'उत्पाद चुनें',

      // Sales
      'sales_dashboard': 'बिक्री डैशबोर्ड',
      'total_revenue': 'कुल राजस्व',
      'completed_sales': 'पूर्ण बिक्री',
      'monthly_overview': 'मासिक बिक्री विवरण',

      // Reminders
      'overdue_reminders': 'बकाया भुगतान रिमाइंडर्स',
      'send_whatsapp_reminder': 'WhatsApp रिमाइंडर भेजें',
      'mark_as_settled': 'जमा के रूप में चिह्नित करें',
    },
  };
}

